cmd_/work5/scheduler/tools/bpf/resolve_btfids/main.o := gcc -Wp,-MD,/work5/scheduler/tools/bpf/resolve_btfids/.main.o.d -Wp,-MT,/work5/scheduler/tools/bpf/resolve_btfids/main.o -g -I/work5/scheduler/tools/include -I/work5/scheduler/tools/include/uapi -I/work5/scheduler/tools/lib/bpf/ -I/work5/scheduler/tools/lib/subcmd/ -D"BUILD_STR(s)=$(pound)s" -c -o /work5/scheduler/tools/bpf/resolve_btfids/main.o main.c

source_/work5/scheduler/tools/bpf/resolve_btfids/main.o := main.c

deps_/work5/scheduler/tools/bpf/resolve_btfids/main.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stddef.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stdarg.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/types/cookie_io_functions_t.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/string.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/unistd.h \
  /usr/include/bits/posix_opt.h \
  /usr/include/bits/environments.h \
  /usr/include/bits/confname.h \
  /usr/include/bits/getopt_posix.h \
  /usr/include/bits/getopt_core.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-float.h \
  /usr/include/libelf.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/elf.h \
  /usr/include/gelf.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/bits/statx.h \
  /work5/scheduler/tools/include/uapi/linux/stat.h \
  /work5/scheduler/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stdbool.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /work5/scheduler/tools/include/uapi/asm/bitsperlong.h \
  /work5/scheduler/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /work5/scheduler/tools/include/asm-generic/bitsperlong.h \
  /work5/scheduler/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/bits/statx-generic.h \
  /usr/include/bits/types/struct_statx_timestamp.h \
  /usr/include/bits/types/struct_statx.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \
  /usr/include/bits/types/struct_iovec.h \
  /usr/include/linux/falloc.h \
  /usr/include/errno.h \
  /usr/include/bits/errno.h \
  /usr/include/linux/errno.h \
  /work5/scheduler/tools/include/uapi/asm/errno.h \
  /work5/scheduler/tools/arch/x86/include/uapi/asm/errno.h \
  /work5/scheduler/tools/include/uapi/asm-generic/errno.h \
  /work5/scheduler/tools/include/uapi/asm-generic/errno-base.h \
  /usr/include/bits/types/error_t.h \
  /work5/scheduler/tools/include/linux/rbtree.h \
  /work5/scheduler/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /work5/scheduler/tools/include/linux/build_bug.h \
  /work5/scheduler/tools/include/linux/compiler.h \
  /work5/scheduler/tools/include/linux/compiler-gcc.h \
  /usr/include/byteswap.h \
  /usr/include/linux/stddef.h \
  /work5/scheduler/tools/include/linux/zalloc.h \
  /work5/scheduler/tools/include/linux/err.h \
  /work5/scheduler/tools/lib/bpf/btf.h \
  /work5/scheduler/tools/include/uapi/linux/btf.h \
  /work5/scheduler/tools/lib/bpf/libbpf_common.h \
  /work5/scheduler/tools/lib/bpf/libbpf.h \
  /work5/scheduler/tools/include/uapi/linux/bpf.h \
  /work5/scheduler/tools/include/uapi/linux/bpf_common.h \
  /work5/scheduler/tools/lib/subcmd/parse-options.h \

/work5/scheduler/tools/bpf/resolve_btfids/main.o: $(deps_/work5/scheduler/tools/bpf/resolve_btfids/main.o)

$(deps_/work5/scheduler/tools/bpf/resolve_btfids/main.o):
