cmd_/work5/scheduler/tools/objtool/objtool.o := gcc -Wp,-MD,/work5/scheduler/tools/objtool/.objtool.o.d -Wp,-MT,/work5/scheduler/tools/objtool/objtool.o -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu89 -g -I/work5/scheduler/tools/include -I/work5/scheduler/tools/arch/x86/include/uapi -I/work5/scheduler/tools/arch/x86/include -I/work5/scheduler/tools/objtool/arch/x86/include -DINSN_USE_ORC -I/work5/scheduler/tools/lib -D"BUILD_STR(s)=$(pound)s" -c -o /work5/scheduler/tools/objtool/objtool.o objtool.c

source_/work5/scheduler/tools/objtool/objtool.o := objtool.c

deps_/work5/scheduler/tools/objtool/objtool.o := \
  /usr/include/stdc-predef.h \
  /usr/include/stdio.h \
  /usr/include/bits/libc-header-start.h \
  /usr/include/features.h \
  /usr/include/sys/cdefs.h \
  /usr/include/bits/wordsize.h \
  /usr/include/bits/long-double.h \
  /usr/include/gnu/stubs.h \
  /usr/include/gnu/stubs-64.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stddef.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stdarg.h \
  /usr/include/bits/types.h \
  /usr/include/bits/typesizes.h \
  /usr/include/bits/types/__fpos_t.h \
  /usr/include/bits/types/__mbstate_t.h \
  /usr/include/bits/types/__fpos64_t.h \
  /usr/include/bits/types/__FILE.h \
  /usr/include/bits/types/FILE.h \
  /usr/include/bits/types/struct_FILE.h \
  /usr/include/bits/stdio_lim.h \
  /usr/include/bits/sys_errlist.h \
  /usr/include/bits/stdio.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stdbool.h \
  /usr/include/string.h \
  /usr/include/bits/types/locale_t.h \
  /usr/include/bits/types/__locale_t.h \
  /usr/include/strings.h \
  /usr/include/stdlib.h \
  /usr/include/bits/waitflags.h \
  /usr/include/bits/waitstatus.h \
  /usr/include/bits/floatn.h \
  /usr/include/bits/floatn-common.h \
  /usr/include/sys/types.h \
  /usr/include/bits/types/clock_t.h \
  /usr/include/bits/types/clockid_t.h \
  /usr/include/bits/types/time_t.h \
  /usr/include/bits/types/timer_t.h \
  /usr/include/bits/stdint-intn.h \
  /usr/include/endian.h \
  /usr/include/bits/endian.h \
  /usr/include/bits/byteswap.h \
  /usr/include/bits/uintn-identity.h \
  /usr/include/sys/select.h \
  /usr/include/bits/select.h \
  /usr/include/bits/types/sigset_t.h \
  /usr/include/bits/types/__sigset_t.h \
  /usr/include/bits/types/struct_timeval.h \
  /usr/include/bits/types/struct_timespec.h \
  /usr/include/bits/pthreadtypes.h \
  /usr/include/bits/thread-shared-types.h \
  /usr/include/bits/pthreadtypes-arch.h \
  /usr/include/alloca.h \
  /usr/include/bits/stdlib-bsearch.h \
  /usr/include/bits/stdlib-float.h \
  /work5/scheduler/tools/lib/subcmd/exec-cmd.h \
  /work5/scheduler/tools/lib/subcmd/pager.h \
  /work5/scheduler/tools/include/linux/kernel.h \
  /usr/include/assert.h \
  /work5/scheduler/tools/include/linux/build_bug.h \
  /work5/scheduler/tools/include/linux/compiler.h \
  /work5/scheduler/tools/include/linux/compiler-gcc.h \
  /work5/scheduler/tools/include/linux/types.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/stdint.h \
  /usr/include/stdint.h \
  /usr/include/bits/wchar.h \
  /usr/include/bits/stdint-uintn.h \
  /usr/include/asm/types.h \
  /usr/include/asm-generic/types.h \
  /usr/include/asm-generic/int-ll64.h \
  /work5/scheduler/tools/arch/x86/include/uapi/asm/bitsperlong.h \
  /work5/scheduler/tools/include/asm-generic/bitsperlong.h \
  /work5/scheduler/tools/include/uapi/asm-generic/bitsperlong.h \
  /usr/include/asm/posix_types.h \
  /usr/include/asm/posix_types_64.h \
  /usr/include/asm-generic/posix_types.h \
  /usr/include/byteswap.h \
  builtin.h \
  /work5/scheduler/tools/lib/subcmd/parse-options.h \
  objtool.h \
  /work5/scheduler/tools/include/linux/list.h \
  /work5/scheduler/tools/include/linux/poison.h \
  /work5/scheduler/tools/include/linux/hashtable.h \
  /work5/scheduler/tools/include/linux/bitops.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/limits.h \
  /usr/lib/gcc/x86_64-redhat-linux/8/include/syslimits.h \
  /usr/include/limits.h \
  /usr/include/bits/posix1_lim.h \
  /usr/include/bits/local_lim.h \
  /usr/include/linux/limits.h \
  /usr/include/bits/posix2_lim.h \
  /work5/scheduler/tools/include/linux/bits.h \
  /work5/scheduler/tools/include/linux/const.h \
  /work5/scheduler/tools/include/vdso/const.h \
  /work5/scheduler/tools/include/uapi/linux/const.h \
  /work5/scheduler/tools/include/vdso/bits.h \
  /work5/scheduler/tools/include/asm-generic/bitops.h \
  /work5/scheduler/tools/include/asm-generic/bitops/__ffs.h \
  /work5/scheduler/tools/include/asm-generic/bitops/__ffz.h \
  /work5/scheduler/tools/include/asm-generic/bitops/fls.h \
  /work5/scheduler/tools/include/asm-generic/bitops/__fls.h \
  /work5/scheduler/tools/include/asm-generic/bitops/fls64.h \
  /work5/scheduler/tools/include/asm-generic/bitops/find.h \
  /work5/scheduler/tools/include/asm-generic/bitops/hweight.h \
  /work5/scheduler/tools/include/asm-generic/bitops/arch_hweight.h \
  /work5/scheduler/tools/include/asm-generic/bitops/const_hweight.h \
  /work5/scheduler/tools/include/asm-generic/bitops/atomic.h \
  /work5/scheduler/tools/include/asm-generic/bitops/non-atomic.h \
  /work5/scheduler/tools/include/linux/hash.h \
  /work5/scheduler/tools/include/linux/log2.h \
  elf.h \
  /usr/include/gelf.h \
  /usr/include/libelf.h \
  /usr/include/elf.h \
  /work5/scheduler/tools/include/linux/rbtree.h \
  /usr/include/linux/stddef.h \
  /work5/scheduler/tools/include/linux/jhash.h \
  /work5/scheduler/tools/include/linux/unaligned/packed_struct.h \
  warn.h \
  /usr/include/sys/stat.h \
  /usr/include/bits/stat.h \
  /usr/include/fcntl.h \
  /usr/include/bits/fcntl.h \
  /usr/include/bits/fcntl-linux.h \

/work5/scheduler/tools/objtool/objtool.o: $(deps_/work5/scheduler/tools/objtool/objtool.o)

$(deps_/work5/scheduler/tools/objtool/objtool.o):
