EXPORT_CALLBACK(__hrtick_start, void, void *)
EXPORT_CALLBACK(active_load_balance_cpu_stop, int, void *)
EXPORT_CALLBACK(cpu_cfs_period_read_u64, u64, struct cgroup_subsys_state *, struct cftype *)
EXPORT_CALLBACK(cpu_cfs_period_write_u64, int, struct cgroup_subsys_state *, struct cftype *, u64)
EXPORT_CALLBACK(cpu_cfs_quota_read_s64, s64, struct cgroup_subsys_state *, struct cftype *)
EXPORT_CALLBACK(cpu_cfs_quota_write_s64, int, struct cgroup_subsys_state *, struct cftype *, s64)
EXPORT_CALLBACK(cpu_cfs_stat_show, int, struct seq_file *, void *)
EXPORT_CALLBACK(cpu_cgroup_attach, void, struct cgroup_taskset *)
EXPORT_CALLBACK(cpu_cgroup_can_attach, int, struct cgroup_taskset *)
EXPORT_CALLBACK(cpu_cgroup_css_alloc, struct cgroup_subsys_state *, struct cgroup_subsys_state *)
EXPORT_CALLBACK(cpu_cgroup_css_free, void, struct cgroup_subsys_state *)
EXPORT_CALLBACK(cpu_cgroup_css_online, int, struct cgroup_subsys_state *)
EXPORT_CALLBACK(cpu_cgroup_css_released, void, struct cgroup_subsys_state *)
EXPORT_CALLBACK(cpu_cgroup_fork, void, struct task_struct *)
EXPORT_CALLBACK(cpu_extra_stat_show, int, struct seq_file *, struct cgroup_subsys_state *)
EXPORT_CALLBACK(cpu_max_show, int, struct seq_file *, void *)
EXPORT_CALLBACK(cpu_max_write, ssize_t, struct kernfs_open_file *, char *, size_t, loff_t)
EXPORT_CALLBACK(cpu_shares_read_u64, u64, struct cgroup_subsys_state *, struct cftype *)
EXPORT_CALLBACK(cpu_shares_write_u64, int, struct cgroup_subsys_state *, struct cftype *, u64)
EXPORT_CALLBACK(cpu_weight_nice_read_s64, s64, struct cgroup_subsys_state *, struct cftype *)
EXPORT_CALLBACK(cpu_weight_nice_write_s64, int, struct cgroup_subsys_state *, struct cftype *, s64)
EXPORT_CALLBACK(cpu_weight_read_u64, u64, struct cgroup_subsys_state *, struct cftype *)
EXPORT_CALLBACK(cpu_weight_write_u64, int, struct cgroup_subsys_state *, struct cftype *, u64)
EXPORT_CALLBACK(default_wake_function, int, wait_queue_entry_t *, unsigned int, int, void *)
EXPORT_CALLBACK(destroy_perf_domain_rcu, void, struct callback_head *)
EXPORT_CALLBACK(destroy_sched_domains_rcu, void, struct callback_head *)
EXPORT_CALLBACK(dl_task_timer, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(free_rootdomain, void, struct callback_head *)
EXPORT_CALLBACK(hrtick, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(idle_inject_timer_fn, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(inactive_task_timer, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(io_schedule_timeout, long int, long int)
EXPORT_CALLBACK(migrate_swap_stop, int, void *)
EXPORT_CALLBACK(migration_cpu_stop, int, void *)
EXPORT_CALLBACK(nohz_csd_func, void, void *)
EXPORT_CALLBACK(pull_dl_task, void, struct rq *)
EXPORT_CALLBACK(pull_rt_task, void, struct rq *)
EXPORT_CALLBACK(push_dl_tasks, void, struct rq *)
EXPORT_CALLBACK(push_rt_tasks, void, struct rq *)
EXPORT_CALLBACK(rt_task_fits_capacity, bool, struct task_struct *, int)
EXPORT_CALLBACK(rto_push_irq_work_func, void, struct irq_work *)
EXPORT_CALLBACK(run_rebalance_domains, void, struct softirq_action *)
EXPORT_CALLBACK(sched_cfs_period_timer, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(sched_cfs_slack_timer, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(sched_cpu_activate, int, unsigned int)
EXPORT_CALLBACK(sched_cpu_deactivate, int, unsigned int)
EXPORT_CALLBACK(sched_cpu_dying, int, unsigned int)
EXPORT_CALLBACK(sched_cpu_starting, int, unsigned int)
EXPORT_CALLBACK(sched_debug_next, void *, struct seq_file *, void *, loff_t *)
EXPORT_CALLBACK(sched_debug_show, int, struct seq_file *, void *)
EXPORT_CALLBACK(sched_debug_start, void *, struct seq_file *, loff_t *)
EXPORT_CALLBACK(sched_debug_stop, void, struct seq_file *, void *)
EXPORT_CALLBACK(sched_energy_aware_handler, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(sched_feat_open, int, struct inode *, struct file *)
EXPORT_CALLBACK(sched_feat_show, int, struct seq_file *, void *)
EXPORT_CALLBACK(sched_feat_write, ssize_t, struct file *, const char *, size_t, loff_t *)
EXPORT_CALLBACK(sched_free_group_rcu, void, struct callback_head *)
EXPORT_CALLBACK(sched_proc_update_handler, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(sched_rr_handler, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(sched_rt_handler, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(sched_rt_period_timer, enum hrtimer_restart, struct hrtimer *)
EXPORT_CALLBACK(sched_tick_remote, void, struct work_struct *)
EXPORT_CALLBACK(schedstat_next, void *, struct seq_file *, void *, loff_t *)
EXPORT_CALLBACK(schedstat_start, void *, struct seq_file *, loff_t *)
EXPORT_CALLBACK(schedstat_stop, void, struct seq_file *, void *)
EXPORT_CALLBACK(sd_ctl_doflags, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(sd_numa_mask, const struct cpumask *, int)
EXPORT_CALLBACK(show_schedstat, int, struct seq_file *, void *)
EXPORT_CALLBACK(sysctl_numa_balancing, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(sysctl_schedstats, int, struct ctl_table *, int, void *, size_t *, loff_t *)
EXPORT_CALLBACK(task_numa_work, void, struct callback_head *)
EXPORT_CALLBACK(tg_nop, int, struct task_group *, void *)
EXPORT_CALLBACK(tg_throttle_down, int, struct task_group *, void *)
EXPORT_CALLBACK(tg_unthrottle_up, int, struct task_group *, void *)
EXPORT_PLUGSCHED(__ia32_sys_nice, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_get_priority_max, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_get_priority_min, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_getaffinity, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_getattr, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_getparam, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_getscheduler, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_rr_get_interval, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_rr_get_interval_time32, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_setaffinity, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_setattr, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_setparam, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__ia32_sys_sched_setscheduler, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__sched_setscheduler, int, struct task_struct *, const struct sched_attr *, bool, bool)
EXPORT_PLUGSCHED(__schedule, void, bool)
EXPORT_PLUGSCHED(__set_cpus_allowed_ptr, int, struct task_struct *, const struct cpumask *, bool)
EXPORT_PLUGSCHED(__x64_sys_nice, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_get_priority_max, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_get_priority_min, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_getaffinity, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_getattr, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_getparam, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_getscheduler, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_rr_get_interval, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_rr_get_interval_time32, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_setaffinity, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_setattr, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_setparam, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(__x64_sys_sched_setscheduler, long int, const struct pt_regs *)
EXPORT_PLUGSCHED(cpuset_cpumask_can_shrink, int, const struct cpumask *, const struct cpumask *)
EXPORT_PLUGSCHED(do_set_cpus_allowed, void, struct task_struct *, const struct cpumask *)
EXPORT_PLUGSCHED(finish_task_switch, struct rq *, struct task_struct *)
EXPORT_PLUGSCHED(get_nohz_timer_target, int, void)
EXPORT_PLUGSCHED(idle_cpu, int, int)
EXPORT_PLUGSCHED(in_sched_functions, int, long unsigned int)
EXPORT_PLUGSCHED(nohz_balance_enter_idle, void, int)
EXPORT_PLUGSCHED(normalize_rt_tasks, void, void)
EXPORT_PLUGSCHED(partition_sched_domains_locked, void, int, struct cpumask * *, struct sched_domain_attr *)
EXPORT_PLUGSCHED(proc_sched_set_task, void, struct task_struct *)
EXPORT_PLUGSCHED(proc_sched_show_task, void, struct task_struct *, struct pid_namespace *, struct seq_file *)
EXPORT_PLUGSCHED(resched_cpu, void, int)
EXPORT_PLUGSCHED(rt_mutex_setprio, void, struct task_struct *, struct task_struct *)
EXPORT_PLUGSCHED(sched_create_group, struct task_group *, struct task_group *)
EXPORT_PLUGSCHED(sched_destroy_group, void, struct task_group *)
EXPORT_PLUGSCHED(sched_exec, void, void)
EXPORT_PLUGSCHED(sched_fork, int, long unsigned int, struct task_struct *)
EXPORT_PLUGSCHED(sched_group_set_shares, int, struct task_group *, long unsigned int)
EXPORT_PLUGSCHED(sched_move_task, void, struct task_struct *)
EXPORT_PLUGSCHED(sched_offline_group, void, struct task_group *)
EXPORT_PLUGSCHED(sched_online_group, void, struct task_group *, struct task_group *)
EXPORT_PLUGSCHED(sched_post_fork, void, struct task_struct *)
EXPORT_PLUGSCHED(sched_set_stop_task, void, int, struct task_struct *)
EXPORT_PLUGSCHED(sched_setscheduler_nocheck, int, struct task_struct *, int, const struct sched_param *)
EXPORT_PLUGSCHED(sched_ttwu_pending, void, void *)
EXPORT_PLUGSCHED(schedule_tail, void, struct task_struct *)
EXPORT_PLUGSCHED(scheduler_tick, void, void)
EXPORT_PLUGSCHED(send_call_function_single_ipi, void, int)
EXPORT_PLUGSCHED(set_user_nice, void, struct task_struct *, long int)
EXPORT_PLUGSCHED(should_numa_migrate_memory, bool, struct task_struct *, struct page *, int, int)
EXPORT_PLUGSCHED(sysrq_sched_debug_show, void, void)
EXPORT_PLUGSCHED(task_can_attach, int, struct task_struct *, const struct cpumask *)
EXPORT_PLUGSCHED(task_numa_fault, void, int, int, int, int)
EXPORT_PLUGSCHED(task_numa_free, void, struct task_struct *, bool)
EXPORT_PLUGSCHED(task_numa_group_id, pid_t, struct task_struct *)
EXPORT_PLUGSCHED(task_rq_lock, struct rq *, struct task_struct *, struct rq_flags *)
EXPORT_PLUGSCHED(task_sched_runtime, long long unsigned int, struct task_struct *)
EXPORT_PLUGSCHED(try_to_wake_up, int, struct task_struct *, unsigned int, int)
EXPORT_PLUGSCHED(wake_up_if_idle, void, int)
EXPORT_PLUGSCHED(wake_up_new_task, void, struct task_struct *)
EXPORT_PLUGSCHED(wake_up_nohz_cpu, void, int)
EXPORT_PLUGSCHED(yield, void, void)
EXPORT_PLUGSCHED(yield_to, int, struct task_struct *, bool)
